#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Tulakann

# Short bio or description (displayed in the header)
description: Just a tiny dust in the galaxy that can code.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /images/blog_avatar.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: tulakan.r@outlook.com
  facebook: tulakanRuangrong
  flickr:
  github: bluenex
  instagram: tulakann
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: tulakann
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: +tulakanRuangrong # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-93059512-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
# url: localhost:4000 # local dev
url: http://bluenex.github.io/old-blog # on web

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

github: [metadata]
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
permalink: /:title/

# The release of Jekyll Now that you're using
version: v3.0.2

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME

# add timezone
timezone: Asia/Bangkok
